sqs.queue.email.ses.events-name=pn-ec-email-ses-events-queue.fifo
sqs.queue.email.ses.events.DLQ-name=pn-ec-email-ses-events-queue-DLQ.fifo
sqs.queue.email.ses.events.errori-name=pn-ec-email-ses-events-errori-queue.fifo
sqs.queue.email.ses.events.errori-DLQ-name=pn-ec-email-ses-events-errori-queue-DLQ.fifo