sqs.queue.ses.events-name=pn-ec-ses-events.fifo
sqs.queue.ses.events.DLQ-name=pn-ec-ses-events-DLQ.fifo
sqs.queue.ses.events.errori-name=pn-ec-ses-events-errori.fifo
sqs.queue.email.ses.events-name=pn-ec-email-ses-events.fifo
sqs.queue.email.ses.events.DLQ-name=pn-ec-email-ses-events-DLQ.fifo
sqs.queue.email.ses.events.errori-name=pn-ec-email-ses-events-errori.fifo