logging.config=classpath:logback-base.xml

logging.level.it.pagopa.pn.ec=${PnEcLoggingLevelRoot:debug}
logging.level.it.pagopa.pn.library.pec=${PnEcLoggingLevelRoot:debug}
#Setting CloudWatch logging level to info, to make CloudWatchMetricPublisher logs visible.
logging.level.software.amazon.awssdk.metrics.publishers.cloudwatch=info

pn.env.runtime=PROD
spring.application.name=PN-ExternalChannel


spring.task.scheduling.pool.size=9

spring.task.execution.pool.max-size=${PnEcTaskExecutionPoolMaxSize:500}

jetty.maxConnectionsPerDestination=${maxConnectionsPerDestination:2048}

spring.codec.max-in-memory-size=${SpringCodecMaxInMemorySize:256KB}

pn.log.trace-id-header=X-Amzn-Trace-Id
pn.log.jti-header=x-pagopa-pn-jti
pn.log.pn-uid-header=x-pagopa-pn-uid
pn.log.pn-cx-type-header=x-pagopa-pn-cx-type
pn.log.pn-cx-groups-header=x-pagopa-pn-cx-groups
pn.log.pn-cx-role-header=x-pagopa-pn-cx-role
pn.log.cx-id-header=x-pagopa-pn-cx-id


management.endpoints.web.exposure.include=health,metrics,loggers

# Parametri di configurazione del TaskExecutor di Spring Boot
#pn.ec.task.execution.pool.max-size=${PnEcTaskExecutionPoolMaxSize}


namirial.warning-to-notdelivered.logic=${PnEcNamirialWarningNotDelivered:true}

sqs.queue.max-message-size=200000
pn.ec.identity.pec=Pn-EC-PEC

#shedlock
pn.ec.shedlock.table-name=pn-EcShedlockCounter
pn.ec.shedlock.lockAtMostFor=${pnEcShedlockAtMostFor:PT15M}
pn.ec.shedlock.lockAtLeastFor=${pnEcShedlockLockAtLeastFor:PT1M}

#consolidatore
pn.ec.consolidatore.max-requests=${ConsolidatoreMaxRequest:600}
pn.ec.consolidatore.refresh-period-seconds=${ConsolidatoreRefreshPeriodSeconds:60}
pn.ec.max-concurrent-requests=${PnEcMaxConsolidatoreConcurrentRequest:10}
pn.ec.max-retry-for-rate-limiter=${PN_EC_MAX_RETRY_FOR_RATE_LIMITER:8}
pn.ec.max-retry-for-rate-limiter-seconds=${PN_EC_MAX_RETRY_FOR_RATE_LIMITER_SECONDS:3}

pn.ec.feature.flag.cartaceo.consolidatore=${PN_EC_FEATURE_SHEDLOCK_RATE_LIMITER_ENABLED:false}


