AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  # WebApiDnsName:
  #   Type: String
  #   Description: 'The DNS name used for WEB rest API.'
  
  # CorsAllowedDomains:
  #   Type: String
  #   Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  # LogsKinesisSourceStreamArn:
  #   Type: String
  #   Description: 'Kinesis stream that receive logs'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  PnEcManagedPolicyName:
    Type: String
    Description: 'Nome della managed policy associata ad External Channel'
    Default: 'PnEcManagedPolicyName'

  PnEcEventBusNameTrackerExternalNotification:
    Type: String
    Description: "Nome del Event Bus per le notifiche verso le piattaforme esterne"

  PnEcEventBusArnTrackerExternalNotification:
    Type: String
    Description: 'ARN del Event Bus per le notifiche verso le piattaforme esterne'

  PnEcTableNameAnagrafica:
    Type: String  
    Description: "Nome della Tabella DynamoDB relativa ad Anagrafica Client"

  PnEcTableArnAnagrafica:
    Type: String
    Description: 'ARN della Tabella DynamoDB relativa ad Anagrafica Client'

  PnEcTableNameRichieste:
    Type: String
    Description: 'Nome della Tabella DynamoDB relativa alle richieste'

  PnEcTableArnRichieste:
    Type: String
    Description: 'ARN della Tabella DynamoDB relativa alle richieste'

  PnEcTableNameRichiesteMetadati:
    Type: String
    Description: 'Nome della Tabella DynamoDB relativa alle richieste'

  PnEcTableArnRichiesteMetadati:
    Type: String
    Description: 'ARN della Tabella DynamoDB relativa alle richieste'

  PnEcQueueNameTrackerStatoSMS:
    Type: String
    Description: '[Notification Tracker: canale SMS] Nome della Coda per aggiornamenti di stato afferenti al canale SMS'

  PnEcQueueArnTrackerStatoSMS:
    Type: String
    Description: '[Notification Tracker: canale SMS] ARN della Coda per aggiornamenti di stato afferenti al canale SMS'

  PnEcQueueUrlTrackerStatoSMS:
    Type: String
    Description: '[Notification Tracker: canale SMS] URL della Coda per aggiornamenti di stato afferenti al canale SMS'

  PnEcQueueNameTrackerErroriSMS:
    Type: String
    Description: '[Notification Tracker: canale SMS] Nome della Coda Errori afferenti al canale SMS'

  PnEcQueueArnTrackerErroriSMS:
    Type: String
    Description: '[Notification Tracker: canale SMS] ARN della Coda Errori afferenti al canale SMS'

  PnEcQueueUrlTrackerErroriSMS:
    Type: String
    Description: '[Notification Tracker: canale SMS] URL della Coda Errori afferenti al canale SMS'

  PnEcQueueNameNotificheExt1:
    Type: String
    Description: '[Notification Tracker: PIATTAFORMA_ESTERNA_1] Nome della Coda per le notifiche a PIATTAFORMA_ESTERNA_1'

  PnEcQueueArnNotificheExt1:
    Type: String
    Description: '[Notification Tracker: PIATTAFORMA_ESTERNA_1] ARN della Coda per le notifiche a PIATTAFORMA_ESTERNA_1'

  PnEcQueueUrlNotificheExt1:
    Type: String
    Description: '[Notification Tracker: PIATTAFORMA_ESTERNA_1] URL della Coda per le notifiche a PIATTAFORMA_ESTERNA_1'

  PnEcSNSNameNotificheExt1:
    Type: String
    Description: '[Notification Tracker: Piattaforme esterne] Nome dello SNS Topic per smistare le notifiche alle Piattaforme esterne'

  PnEcSNSArnNotificheExt1:
    Type: String
    Description: '[Notification Tracker: Piattaforme esterne] ARN dello SNS Topic per smistare le notifiche alle Piattaforme esterne'

  PnEcQueueNameBatchSMS:
    Type: String
    Description: '[Canale SMS] Nome della Coda per la modalità SMS-Batch'

  PnEcQueueArnBatchSMS:
    Type: String
    Description: '[Canale SMS] ARN della Coda per la modalità SMS-Batch'

  PnEcQueueUrlBatchSMS:
    Type: String
    Description: '[Canale SMS] URL della Coda per la modalità SMS-Batch'

  PnEcQueueNameInteractiveSMS:
    Type: String
    Description: '[Canale SMS] Nome della Coda per la modalità SMS-Interactive'

  PnEcQueueArnInteractiveSMS:
    Type: String
    Description: '[Canale SMS] ARN della Coda per la modalità SMS-Interactive'

  PnEcQueueUrlInteractiveSMS:
    Type: String
    Description: '[Canale SMS] URL della Coda per la modalità SMS-Interactive'

  PnEcQueueNameErroriSMS:
    Type: String
    Description: '[Canale SMS] Nome della Coda Errori SMS'

  PnEcQueueArnErroriSMS:
    Type: String
    Description: '[Canale SMS] ARN della Coda Errori SMS'

  PnEcQueueUrlErroriSMS:
    Type: String
    Description: '[Canale SMS] URL della Coda Errori SMS'

Resources:

  # PN-TemplateBeMs microservice
  ExternalChannelMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-external-channel'
        CpuValue: 512
        MemoryAmount: 2GB
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PnEcTableNameAnagrafica=${PnEcTableNameAnagrafica}'
        ContainerEnvEntry3: !Sub 'PnEcTableNameRichieste=${PnEcTableNameRichieste}'
        ContainerEnvEntry4: !Sub 'PnEcTableNameRichiesteMetadati=${PnEcTableNameRichiesteMetadati}'
        ContainerEnvEntry5: !Sub 'PnEcSNSNameNotificheExt1=${PnEcSNSNameNotificheExt1}'
        ContainerEnvEntry6: !Sub 'PnEcSNSArnNotificheExt1=${PnEcSNSArnNotificheExt1}'
        ContainerEnvEntry7: !Sub 'PnEcQueueNameNotificheExt1=${PnEcQueueNameNotificheExt1}'
        ContainerEnvEntry8: !Sub 'PnEcEventBusNameTrackerExternalNotification=${PnEcEventBusNameTrackerExternalNotification}'
        ContainerEnvEntry9: !Sub 'PnEcQueueNameTrackerStatoSMS=${PnEcQueueNameTrackerStatoSMS}'
        ContainerEnvEntry10: !Sub 'PnEcQueueNameTrackerErroriSMS=${PnEcQueueNameTrackerErroriSMS}'
        ContainerEnvEntry11: !Sub 'PnEcQueueNameBatchSMS=${PnEcQueueNameBatchSMS}'
        ContainerEnvEntry12: !Sub 'PnEcQueueNameInteractiveSMS=${PnEcQueueNameInteractiveSMS}'
        ContainerEnvEntry13: !Sub 'PnEcQueueNameErroriSMS=${PnEcQueueNameErroriSMS}'
        ContainerEnvEntry14: !Sub 'StateMachineBaseUrl=${ApplicationLoadBalancerDomain}'
        ContainerEnvEntry15: !Sub 'SafeStorageBaseUrl=${ApplicationLoadBalancerDomain}'
        MappedPaths: '/external-channels/*,/external-channel/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        # CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
        TaskRoleManagedPolicyArn: !Ref PnEcManagedPolicy
        # HealthCheckPath:  

  PnEcManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'String'
      ManagedPolicyName: !Ref PnEcManagedPolicyName
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:*GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:Describe*'
              - 'dynamodb:Scan'
              - 'dynamodb:List*'
              - 'dynamodb:Batch*'
              - 'dynamodb:PartiQL*'
              - 'dynamodb:Update*'
              - 'dynamodb:Put*'
            Resource:
              - !Sub '${PnEcTableArnAnagrafica}'
              - !Sub '${PnEcTableArnRichieste}'
              - !Sub '${PnEcTableArnRichiesteMetadati}'
          - Effect: Allow
            Action:
              - 'sqs:ReceiveMessage'
              - 'sqs:DeleteMessage'
              - 'sqs:PurgeQueue'
              - 'sqs:SendMessage'
            Resource:
              - !Sub '${PnEcQueueArnTrackerStatoSMS}'
              - !Sub '${PnEcQueueArnTrackerErroriSMS}'
              - !Sub '${PnEcQueueArnNotificheExt1}'
              - !Sub '${PnEcQueueArnBatchSMS}'
              - !Sub '${PnEcQueueArnInteractiveSMS}'
              - !Sub '${PnEcQueueArnErroriSMS}'
          - Effect: Allow
            Action:
              - 'events:DescribeEventBus'
              - 'events:List*'
              - 'events:PutEvents'
            Resource:
              - !Sub '${PnEcEventBusArnTrackerExternalNotification}'

  PnEcQueuePolicyTrackerStatoSMS:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Sub '${PnEcQueueUrlTrackerStatoSMS}' 
      PolicyDocument: 
        Statement: 
          - Action: 
              - "SQS:*"
            Effect: "Allow"
            Resource: !Sub ${PnEcQueueArnTrackerStatoSMS}
            Principal:  
              AWS: 
                - !Join [ '', [ !Sub 'arn:aws:iam::${AWS::AccountId}:role/' , !GetAtt ExternalChannelMicroservice.Outputs.TaskRoleName]]

  PnEcQueuePolicyTrackerErroriSMS:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Sub '${PnEcQueueUrlTrackerErroriSMS}'
      PolicyDocument: 
        Statement: 
          - Action: 
              - "SQS:*"
            Effect: "Allow"
            Resource: !Sub ${PnEcQueueArnTrackerErroriSMS}
            Principal:  
              AWS: 
                - !Join [ '', [ !Sub 'arn:aws:iam::${AWS::AccountId}:role/' , !GetAtt ExternalChannelMicroservice.Outputs.TaskRoleName]]

  PnEcQueuePolicyNotificheExt1:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Sub '${PnEcQueueUrlNotificheExt1}' 
      PolicyDocument: 
        Statement: 
          - Action: 
              - "SQS:*"
            Effect: "Allow"
            Resource: !Sub ${PnEcQueueArnNotificheExt1}
            Principal:  
              AWS: 
                - !Join [ '', [ !Sub 'arn:aws:iam::${AWS::AccountId}:role/' , !GetAtt ExternalChannelMicroservice.Outputs.TaskRoleName]]

  PnEcQueuePolicyBatchSMS:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Sub '${PnEcQueueUrlBatchSMS}' 
      PolicyDocument: 
        Statement: 
          - Action: 
              - "SQS:*"
            Effect: "Allow"
            Resource: !Sub ${PnEcQueueArnBatchSMS}
            Principal:  
              AWS: 
                - !Join [ '', [ !Sub 'arn:aws:iam::${AWS::AccountId}:role/' , !GetAtt ExternalChannelMicroservice.Outputs.TaskRoleName]]

  PnEcQueuePolicyInteractiveSMS:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Sub '${PnEcQueueUrlInteractiveSMS}' 
      PolicyDocument: 
        Statement: 
          - Action: 
              - "SQS:*"
            Effect: "Allow"
            Resource: !Sub ${PnEcQueueArnInteractiveSMS}
            Principal:  
              AWS: 
                - !Join [ '', [ !Sub 'arn:aws:iam::${AWS::AccountId}:role/' , !GetAtt ExternalChannelMicroservice.Outputs.TaskRoleName]]

  PnEcQueuePolicyErroriSMS:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Sub '${PnEcQueueUrlErroriSMS}' 
      PolicyDocument: 
        Statement: 
          - Action: 
              - "SQS:*"
            Effect: "Allow"
            Resource: !Sub ${PnEcQueueArnErroriSMS}
            Principal:  
              AWS: 
                - !Join [ '', [ !Sub 'arn:aws:iam::${AWS::AccountId}:role/' , !GetAtt ExternalChannelMicroservice.Outputs.TaskRoleName]]

  PnEcEventBusPolicyECSTrackerExternalNotification:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref PnEcEventBusNameTrackerExternalNotification
      StatementId: 'PnEcCustomEventBusPolicyAllowECS'
      Statement:
        Action: 
          - "events:PutEvents"
          - 'events:DescribeEventBus'
          - 'events:List*'
        Effect: "Allow"
        Principal: 
          Service:
          - 'ecs.amazonaws.com'
        Resource: !Ref PnEcEventBusArnTrackerExternalNotification

  # PnEcEventBusPolicyDenyTrackerExternalNotification:
  #   Type: AWS::Events::EventBusPolicy
  #   Properties:
  #     EventBusName: !Ref PnEcEventBusNameTrackerExternalNotification
  #     StatementId: 'PnEcCustomEventBusPolicyDenyCrossAccount'
  #     Statement:
  #       Action: 
  #         - "events:*"
  #       Effect: 'Deny'
  #       Principal: 
  #         Service:
  #           - 'ecs.amazonaws.com'
  #       Resource: !Ref PnEcEventBusArnTrackerExternalNotification
  #       Condition:
  #         StringNotEquals:
  #           aws:SourceAccount: !Sub '${AWS::AccountId}'

  PnEcEventBusPolicyManageTrackerExternalNotification:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref PnEcEventBusNameTrackerExternalNotification
      StatementId: 'PnEcCustomEventBusPolicyManage'
      Statement:
        Action: 
          - 'events:PutRule'
          - 'events:PutTargets'
          - 'events:DeleteRule'
          - 'events:RemoveTargets'
          - 'events:DisableRule'
          - 'events:EnableRule'
          - 'events:TagResource'
          - 'events:UntagResource'
          - 'events:DescribeRule'
          - 'events:ListTargetsByRule'
          - 'events:ListTagsForResource'
        Effect: 'Allow'
        Principal: 
          AWS: !Sub '${AWS::AccountId}'
        Resource: !Ref PnEcEventBusArnTrackerExternalNotification
        Condition:
          StringEqualsIfExists:
            events:creatorAccount: !Sub '${AWS::AccountId}'