logging.config=config/logback-local.xml
# Runtime mode
pn.env.runtime=DEVELOPMENT


server.port=8080
pn.analyzer.cloudwatch-metric-cron=-

pn.ec.commons.endpoint.external-channel.container-base-url=http://localhost:8080
pn.ec.commons.endpoint.safe-storage.container-base-url=http://localhost:8081
pn.ec.statemachine.endpoint.container-base-url=http://localhost:8082
pn.ec.commons.endpoint.consolidatore.base-url=http://localhost:1080
pn.ec.pdfraster.endpoint.base-url=http://localhost:8084

pn.ec.commons.endpoint.safe-storage.client-header-value=pn-external-channels
pn.ec.commons.endpoint.safe-storage.api-key-header-value=pn-external-channels_api_key
pn.ec.email.default-sender-address=noreply@mail.dev.notifichedigitali.it

pn.ec.commons.ricezione-esiti-cartaceo.consider-event-without-sent-status-as-booked=true
pn.ec.commons.ricezione-esiti-cartaceo.allowed-future-offset-duration=1m
pn.ec.commons.ricezione-esiti-cartaceo.duplicates-check=productType1;productType2;productType3
pn.ec.cartaceo.paper.document-type-to-transform=PN_NOTIFICATION_ATTACHMENTS
pn.ec.cartaceo.paper.document-type-for-rasterized=PN_PAPER_ATTACHMENT
pn.ec.cartaceo.paper.document-type-for-normalized=PN_CLEAN_PAPER_ATTACHMENT
pn.ec.cartaceo.paper.pa-id-to-raster=15376371009
pn.ec.cartaceo.paper.pa-id-to-normalize=PA1;PA2
pn.ec.cartaceo.paper.pa-id-override=15376371009

namirial.server.imap.address=send.sicurezzapostale.it
namirial.server.smtp.address=send.sicurezzapostale.it
namirial.server.imap.port=993
namirial.server.smtp.port=465
namirial.pool.imap.maxtotal=10
namirial.pool.imap.maxidle=10
namirial.pool.imap.minidle=1
namirial.pool.smtp.maxtotal=40
namirial.pool.smtp.maxidle=40
namirial.pool.smtp.minidle=1
namirial.server.cache=false
namirial.server.cache.endpoint=
namirial.metric.duplicate.receipt.namespace=PnEcNamirialMetricDuplicateReceiptNamespace
namirial.metric.duplicate.receipt.name=PnEcNamirialMetricDuplicateReceiptName
pn.ec.pec.namirial-warning-to-notdelivered-logic=true

pn.ec.pec.identity=Pn-EC-PEC
pn.ec.cron.gestione-retry-cartaceo=${PnEcCronGestioneRetryCartaceo:0 */5 * * * *}
pn.ec.pec.attachment-rule=FIRST
pn.ec.pec.max-message-size-mb=30
pn.ec.pec.tipo-ricevuta-breve=false;2024-03-14T23:00:00Z;true
pn.ec.pec.pn-pec-provider-switch-read=1970-01-01T00:00:00Z;dummy
pn.ec.pec.pn-pec-provider-switch-write=1970-01-01T00:00:00Z;dummy



pn.ec.storage.staging-bucket=pn-sqs-messages-staging
pn.ec.pec.tipo-ricevuta-header-name=X-TipoRicevuta
pn.ec.pec.tipo-ricevuta-header-value=breve


pn.ec.pec.dimension-metrics-schema=Pn-EC-Pec-MetricsSchema

pn.ec.cancellazione-ricevute-pec.sqs-queue-name=pn-ec-pec-cancellazione-ricevute-queue

pn.ec.notification-tracker.event-bridge.notifications-bus-name=notifications-bus-name-test

pn.ec.pdfraster.pdf-conversion-expiration-offset-in-days=1
pn.ec.delay.lavorazione-batch-cartaceo=300000

pn.ec.cron.lavorazione-batch-cartaceo=0 */1 * * * *
pn.ec.cron.lavorazione-batch-pec=0 */5 * * * *
pn.ec.cron.gestione-retry-pec=0 */5 * * * *

## AWS specific configurations
aws.endpoint-url=http://127.0.0.1:4566
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.region-code=us-east-1

test.aws.sqs.endpoint=${aws.endpoint-url}
test.aws.event=${aws.endpoint-url}
test.aws.dynamodb.endpoint=${aws.endpoint-url}
test.aws.sns.endpoint=${aws.endpoint-url}
test.aws.ses.endpoint=${aws.endpoint-url}
test.aws.secretsmanager.endpoint=${aws.endpoint-url}
test.aws.cloudwatch.endpoint=${aws.endpoint-url}
test.aws.ssm.endpoint=${aws.endpoint-url}
test.aws.s3.endpoint=${aws.endpoint-url}
test.aws.region-code=${aws.region-code}

spring.cloud.aws.credentials.profile.name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.sqs.endpoint=${aws.endpoint-url}


pn.ec.sqs.max-message-size=200000


pn.ec.pec.max-thread-pool-size=50



pn.ec.sqs.timeout.percent=10
pn.ec.sqs.timeout.managed-queues=pn-ec-email-batch-queue.fifo,pn-ec-email-interactive-queue.fifo,pn-ec-email-errori-queue.fifo,pn-ec-cartaceo-batch-queue.fifo,pn-ec-cartaceo-errori-queue.fifo,pn-ec-pec-scaricamento-esiti-queue.fifo,pn-ec-email-ses-events-queue
pn.ec.sqs.timeout.default-seconds=86400

#shedlock
pn.ec.commons.shedlock.table-name=pn-EcShedlockCounter
#rateLimiter
pn.ec.commons.consolidatore.rate-limiter.max-requests=2
pn.ec.commons.consolidatore.rate-limiter.refresh-period-seconds=60

pn.ec.feature.flag.cartaceo.consolidatore=true
